server:
  port: 8080

spring:
  application:
    name: kotlin-spring-coupon

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:coupon_system_db;MODE=MySQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
